require('dotenv').config();
const mongoose = require('mongoose');
const { Transaction } = require('./server/models');

mongoose
  .connect(
    process.env.MONGODB_URI, {
      useNewUrlParser: true,
    },
  );

const transactionSeed = [
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Mongoose',
    price: 1299.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-02-03',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-02-15',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-02-22',
  },
  {
    itemName: 'Mongoose',
    price: 1299.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-02-28',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-02',
  },
  {
    itemName: 'Cannondale',
    price: 750.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-05',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
  {
    itemName: 'Trek X-Caliber 8',
    price: 1199.99,
    quantity: 1,
    departmentName: 'Bikes',
    storeName: 'New York',
    transactionDate: '2017-01-08',
  },
];

Transaction
  .remove({})
  .then(() => Transaction.collection.insertMany(transactionSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
