export const GET_TOPSELLINGITEMSBYPRICE = 'GET_TOPSELLINGITEMSBYPRICE';
export const GET_TOPSELLINGITEMSBYQUANTITY = 'GET_TOPSELLINGITEMSBYQUANTITY';
export const GET_TOPPERFORMINGSTORES = 'GET_TOPPERFORMINGSTORES';
