export const GET_TOPSELLINGITEMSBYPRICE = 'GET_TOPSELLINGITEMSBYPRICE';
export const GET_TOPSELLINGITEMSBYQUANTITY = 'GET_TOPSELLINGITEMSBYQUANTITY';
export const GET_TOPPERFORMINGSTORES = 'GET_TOPPERFORMINGSTORES';
export const GET_SALESDISTRIBUTIONBYSTORE = 'GET_SALESDISTRIBUTIONBYSTORE';
export const GET_YEARLYPERFORMANCE = 'GET_YEARLYPERFORMANCE';
export const GET_GOALSDATA = 'GET_GOALSDATA';
